version: '3.7'

services:
  # web:
  #   build: .
  #   container_name: api_django_post
  #   command: python manage.py runserver 0.0.0.0:8000
  #   ports:
  #     - 8000:8000
  #   depends_on:
  #     - db

  db:
    image: postgres:latest
    restart: always
    container_name: db_postgres
    env_file:
      - db.env
    ports:
      - 5432:5432
